# Your Name or Company
title: Zhiyuan Wang SE Intern

# Description of your website. This is used for social sharing.
description:  A website for Zhiyuan Wang

# A brief blurb about yourself
content:  

 Tech Stack 
 Backend JavaSE + SpringBoot, Frontend React, Container K8s, Cloud AWS
 Machine Learning Frameworks 
 TensorFlow, PyTorch, Scikit‑learn, Keras 
 Data Science Tools 
 Pandas, NumPy, Matplotlib, Seaborn

 About Me
 I am a passionate Software Development Engineer with a strong foundation in developing, and optimizing software solutions. I thrive in craft
 ing efficient and scalable applications. I enjoy problem‑solving, collaborating in dynamic team environments, and continuously learning about
 emerging technologies to deliver impactful results. My goal is to create software that not only meets business needs but also enhances user
 experiences.
# Add your social links
social:
  - platform: Github
    url: https://github.com/SamWang3047
  - platform: Linkedin
    url: https://www.linkedin.com/in/zhiyuan-wang-250119256/
  - platform: LeetcodeCN
    url: https://leetcode.cn/u/samwang3047/
  - platform: Leetcode
    url: https://leetcode.com/SamWang3047/
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
