# Your Name or Company
title: Zhiyuan Wang SE

# Description of your website. This is used for social sharing.
description:  A website for Zhiyuan Wang

# A brief blurb about yourself
content: |  
  <p><strong>Tech Stack</strong><br>
  Backend: <strong>Java + Spring Boot, Redis + MyBatis, Apache Kafka</strong>, Frontend: <strong>React</strong>, Container: <strong>K8s</strong>, Cloud: <strong>AWS</strong></p>

  <p><strong>Machine Learning Frameworks</strong><br>
  <strong>TensorFlow</strong>, <strong>PyTorch</strong>, <strong>Scikit-learn</strong>, <strong>Keras</strong></p>

  <p><strong>Data Science Tools</strong><br>
  <strong>Pandas</strong>, <strong>NumPy</strong>, <strong>Matplotlib</strong>, <strong>Seaborn</strong></p>

  <p><strong>About Me</strong><br>
  I am a <strong>passionate Software Development Engineer</strong> with a strong foundation in <strong>developing</strong> and <strong>optimizing software solutions</strong>.  
  I thrive in crafting efficient, scalable applications and enjoy <strong>problem-solving</strong>, <strong>team collaboration</strong>, and exploring emerging technologies.  
  My goal is to create software that not only meets business needs but also enhances user experiences.</p>

# Add your social links
social:
  - platform: Github
    url: https://github.com/SamWang3047
  - platform: Linkedin
    url: https://www.linkedin.com/in/zhiyuan-wang-250119256/
  - platform: LeetcodeCN
    url: https://leetcode.cn/u/samwang3047/
  - platform: Leetcode
    url: https://leetcode.com/SamWang3047/
  - platform: Projects
    url: https://drive.google.com/drive/folders/1ro9s_R3kue0e-wwW76COhVv9T46efVAK?usp=sharing
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
