# Your Name or Company
title: Zhiyuan Wang SE Intern

# Description of your website. This is used for social sharing.
description:  A website for Zhiyuan Wang

# A brief blurb about yourself
content:  22-year-old from Beijing, China, who has decided to pursue a career in Melbourne. Undergraduate major in Software Engineering, and Currently enrolled in the MIT program at the University of Melbourne.
          I strongly believe that love is the best teacher and motivator, and I am committed to applying my knowledge and skills to my work in the software engineering field.
          KEYWORDS：Java, Spring Boot, Linux, Algorithm
# Add your social links
social:
  - platform: Github
    url: https://github.com/SamWang3047
  - platform: Facebook
    url: https://www.facebook.com/profile.php?id=100005703558242
  - platform: Twitter
    url: https://twitter.com/SamWang70144014
  - platform: Linkedin
    url: https://www.linkedin.com/in/zhiyuan-wang-250119256/
  - platform: LeetcodeCN
    url: https://leetcode.cn/u/samwang3047/
  - platform: Leetcode
    url: https://leetcode.com/SamWang3047/
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
