# Your Name or Company
title: Zhiyuan Wang SE

# Description of your website. This is used for social sharing.
description:  A website for Zhiyuan Wang

# A brief blurb about yourself
# About Section (move this to index.md or _data/about.yml if not rendering)
about:
  tech_stack: 
    - Backend: JavaSE + Spring Boot
    - Frontend: React
    - Container: Kubernetes (K8s)
    - Cloud: AWS
  machine_learning_frameworks:
    - TensorFlow
    - PyTorch
    - Scikit-learn
    - Keras
  data_science_tools:
    - Pandas
    - NumPy
    - Matplotlib
    - Seaborn
  summary: |
    I am a passionate Software Development Engineer with a strong foundation in developing and optimizing software solutions. 
    I thrive in crafting efficient, scalable applications and enjoy problem-solving, dynamic team collaboration, and exploring emerging technologies.

# Add your social links
social:
  - platform: Github
    url: https://github.com/SamWang3047
  - platform: Linkedin
    url: https://www.linkedin.com/in/zhiyuan-wang-250119256/
  - platform: LeetcodeCN
    url: https://leetcode.cn/u/samwang3047/
  - platform: Leetcode
    url: https://leetcode.com/SamWang3047/
# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
